# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.rates_by_base_response import RatesByBaseResponse

class TestRatesByBaseResponse(unittest.TestCase):
    """RatesByBaseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RatesByBaseResponse:
        """Test RatesByBaseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RatesByBaseResponse`
        """
        model = RatesByBaseResponse()
        if include_optional:
            return RatesByBaseResponse(
                base = '',
                var_date = '',
                requested_date = '',
                as_of = {
                    'key' : ''
                    },
                rates = {
                    'key' : 1.337
                    },
                ppp = currencycore.models.rates_by_base_response_ppp.RatesByBaseResponse_ppp(
                    base = '', 
                    year = 1.337, 
                    values = {
                        'key' : 1.337
                        }, )
            )
        else:
            return RatesByBaseResponse(
                base = '',
                var_date = '',
                rates = {
                    'key' : 1.337
                    },
        )
        """

    def testRatesByBaseResponse(self):
        """Test RatesByBaseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
