# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.mean_reversion_response import MeanReversionResponse

class TestMeanReversionResponse(unittest.TestCase):
    """MeanReversionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeanReversionResponse:
        """Test MeanReversionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeanReversionResponse`
        """
        model = MeanReversionResponse()
        if include_optional:
            return MeanReversionResponse(
                base = '',
                var_from = '',
                to = '',
                universe = 'liquid',
                results = [
                    currencycore.models.mean_reversion_response_results_inner.MeanReversionResponse_results_inner(
                        currency = '', 
                        score = 1.337, 
                        deviation_pct = 1.337, 
                        reversion_frequency = 1.337, 
                        half_life_days = 1.337, 
                        note = '', )
                    ]
            )
        else:
            return MeanReversionResponse(
                base = '',
                var_from = '',
                to = '',
                results = [
                    currencycore.models.mean_reversion_response_results_inner.MeanReversionResponse_results_inner(
                        currency = '', 
                        score = 1.337, 
                        deviation_pct = 1.337, 
                        reversion_frequency = 1.337, 
                        half_life_days = 1.337, 
                        note = '', )
                    ],
        )
        """

    def testMeanReversionResponse(self):
        """Test MeanReversionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
