# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.safe_haven_response_crisis import SafeHavenResponseCrisis

class TestSafeHavenResponseCrisis(unittest.TestCase):
    """SafeHavenResponseCrisis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SafeHavenResponseCrisis:
        """Test SafeHavenResponseCrisis
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SafeHavenResponseCrisis`
        """
        model = SafeHavenResponseCrisis()
        if include_optional:
            return SafeHavenResponseCrisis(
                label = '',
                var_from = '',
                to = ''
            )
        else:
            return SafeHavenResponseCrisis(
                label = '',
                var_from = '',
                to = '',
        )
        """

    def testSafeHavenResponseCrisis(self):
        """Test SafeHavenResponseCrisis"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
