# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.rates_response import RatesResponse

class TestRatesResponse(unittest.TestCase):
    """RatesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RatesResponse:
        """Test RatesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RatesResponse`
        """
        model = RatesResponse()
        if include_optional:
            return RatesResponse(
                var_date = '',
                base = 'USD',
                rates = {
                    'key' : 1.337
                    },
                requested_date = '',
                as_of = {
                    'key' : ''
                    }
            )
        else:
            return RatesResponse(
                var_date = '',
                base = 'USD',
                rates = {
                    'key' : 1.337
                    },
        )
        """

    def testRatesResponse(self):
        """Test RatesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
