# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.volatility_response import VolatilityResponse

class TestVolatilityResponse(unittest.TestCase):
    """VolatilityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VolatilityResponse:
        """Test VolatilityResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VolatilityResponse`
        """
        model = VolatilityResponse()
        if include_optional:
            return VolatilityResponse(
                base = '',
                var_from = '',
                to = '',
                mode = 'compare',
                sort = 'stable',
                universe = 'liquid',
                basis = 'annualized-daily',
                results = [
                    currencycore.models.volatility_response_results_inner.VolatilityResponse_results_inner(
                        currency = '', 
                        volatility = 1.337, 
                        observations = 1.337, 
                        note = '', )
                    ]
            )
        else:
            return VolatilityResponse(
                base = '',
                var_from = '',
                to = '',
                mode = 'compare',
                basis = 'annualized-daily',
                results = [
                    currencycore.models.volatility_response_results_inner.VolatilityResponse_results_inner(
                        currency = '', 
                        volatility = 1.337, 
                        observations = 1.337, 
                        note = '', )
                    ],
        )
        """

    def testVolatilityResponse(self):
        """Test VolatilityResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
