# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.drawdown_response import DrawdownResponse

class TestDrawdownResponse(unittest.TestCase):
    """DrawdownResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DrawdownResponse:
        """Test DrawdownResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DrawdownResponse`
        """
        model = DrawdownResponse()
        if include_optional:
            return DrawdownResponse(
                base = '',
                var_from = '',
                to = '',
                mode = 'compare',
                sort = 'deepest',
                universe = 'liquid',
                results = [
                    currencycore.models.drawdown_response_results_inner.DrawdownResponse_results_inner(
                        currency = '', 
                        max_drawdown_pct = 1.337, 
                        peak_date = '', 
                        trough_date = '', 
                        recovery_date = '', 
                        recovery_days = 1.337, 
                        note = '', )
                    ]
            )
        else:
            return DrawdownResponse(
                base = '',
                var_from = '',
                to = '',
                mode = 'compare',
                results = [
                    currencycore.models.drawdown_response_results_inner.DrawdownResponse_results_inner(
                        currency = '', 
                        max_drawdown_pct = 1.337, 
                        peak_date = '', 
                        trough_date = '', 
                        recovery_date = '', 
                        recovery_days = 1.337, 
                        note = '', )
                    ],
        )
        """

    def testDrawdownResponse(self):
        """Test DrawdownResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
