# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.currencies_response_inner import CurrenciesResponseInner

class TestCurrenciesResponseInner(unittest.TestCase):
    """CurrenciesResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurrenciesResponseInner:
        """Test CurrenciesResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CurrenciesResponseInner`
        """
        model = CurrenciesResponseInner()
        if include_optional:
            return CurrenciesResponseInner(
                code = '',
                numeric = '',
                name = '',
                symbol = ''
            )
        else:
            return CurrenciesResponseInner(
                code = '',
                numeric = '',
                name = '',
                symbol = '',
        )
        """

    def testCurrenciesResponseInner(self):
        """Test CurrenciesResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
