# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.api.currency_core_api import CurrencyCoreApi


class TestCurrencyCoreApi(unittest.TestCase):
    """CurrencyCoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CurrencyCoreApi()

    def tearDown(self) -> None:
        pass

    def test_ai(self) -> None:
        """Test case for ai

        AI
        """
        pass

    def test_convert(self) -> None:
        """Test case for convert

        Convert
        """
        pass

    def test_correlation(self) -> None:
        """Test case for correlation

        Correlation
        """
        pass

    def test_countries(self) -> None:
        """Test case for countries

        Countries
        """
        pass

    def test_currencies(self) -> None:
        """Test case for currencies

        Currencies
        """
        pass

    def test_drawdown(self) -> None:
        """Test case for drawdown

        Drawdown
        """
        pass

    def test_history(self) -> None:
        """Test case for history

        History
        """
        pass

    def test_history_analysis(self) -> None:
        """Test case for history_analysis

        History analysis
        """
        pass

    def test_mean_reversion(self) -> None:
        """Test case for mean_reversion

        Mean reversion
        """
        pass

    def test_ppp_analysis(self) -> None:
        """Test case for ppp_analysis

        PPP analysis
        """
        pass

    def test_rates(self) -> None:
        """Test case for rates

        Rates
        """
        pass

    def test_rates_by_base(self) -> None:
        """Test case for rates_by_base

        Rates by base
        """
        pass

    def test_safe_haven(self) -> None:
        """Test case for safe_haven

        Safe haven
        """
        pass

    def test_volatility(self) -> None:
        """Test case for volatility

        Volatility
        """
        pass


if __name__ == '__main__':
    unittest.main()
