# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.history_analysis_response import HistoryAnalysisResponse

class TestHistoryAnalysisResponse(unittest.TestCase):
    """HistoryAnalysisResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistoryAnalysisResponse:
        """Test HistoryAnalysisResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistoryAnalysisResponse`
        """
        model = HistoryAnalysisResponse()
        if include_optional:
            return HistoryAnalysisResponse(
                base = '',
                var_from = '',
                to = '',
                mode = 'compare',
                sort = 'strengthened',
                asset_class = 'fiat',
                interval = 'daily',
                stats = True,
                results = [
                    currencycore.models.history_analysis_response_results_inner.HistoryAnalysisResponse_results_inner(
                        currency = '', 
                        start_date = '', 
                        end_date = '', 
                        start_rate = 1.337, 
                        end_rate = 1.337, 
                        change_pct = 1.337, 
                        strengthened_pct = 1.337, 
                        stats = currencycore.models.history_analysis_response_results_inner_stats.HistoryAnalysisResponse_results_inner_stats(
                            min = 1.337, 
                            max = 1.337, 
                            avg = 1.337, ), 
                        series = {
                            'key' : 1.337
                            }, 
                        volatility = 1.337, 
                        note = '', )
                    ]
            )
        else:
            return HistoryAnalysisResponse(
                base = '',
                var_from = '',
                to = '',
                mode = 'compare',
                stats = True,
                results = [
                    currencycore.models.history_analysis_response_results_inner.HistoryAnalysisResponse_results_inner(
                        currency = '', 
                        start_date = '', 
                        end_date = '', 
                        start_rate = 1.337, 
                        end_rate = 1.337, 
                        change_pct = 1.337, 
                        strengthened_pct = 1.337, 
                        stats = currencycore.models.history_analysis_response_results_inner_stats.HistoryAnalysisResponse_results_inner_stats(
                            min = 1.337, 
                            max = 1.337, 
                            avg = 1.337, ), 
                        series = {
                            'key' : 1.337
                            }, 
                        volatility = 1.337, 
                        note = '', )
                    ],
        )
        """

    def testHistoryAnalysisResponse(self):
        """Test HistoryAnalysisResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
