# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.correlation_response import CorrelationResponse

class TestCorrelationResponse(unittest.TestCase):
    """CorrelationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorrelationResponse:
        """Test CorrelationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorrelationResponse`
        """
        model = CorrelationResponse()
        if include_optional:
            return CorrelationResponse(
                base = '',
                var_from = '',
                to = '',
                results = [
                    currencycore.models.correlation_response_results_inner.CorrelationResponse_results_inner(
                        currency = '', 
                        correlation = 1.337, 
                        observations = 1.337, 
                        note = '', )
                    ]
            )
        else:
            return CorrelationResponse(
                base = '',
                var_from = '',
                to = '',
                results = [
                    currencycore.models.correlation_response_results_inner.CorrelationResponse_results_inner(
                        currency = '', 
                        correlation = 1.337, 
                        observations = 1.337, 
                        note = '', )
                    ],
        )
        """

    def testCorrelationResponse(self):
        """Test CorrelationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
