# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.ppp_analysis_response import PppAnalysisResponse

class TestPppAnalysisResponse(unittest.TestCase):
    """PppAnalysisResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PppAnalysisResponse:
        """Test PppAnalysisResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PppAnalysisResponse`
        """
        model = PppAnalysisResponse()
        if include_optional:
            return PppAnalysisResponse(
                var_from = 1.337,
                to = 1.337,
                mode = 'compare',
                sort = 'increased',
                stats = True,
                results = [
                    currencycore.models.ppp_analysis_response_results_inner.PppAnalysisResponse_results_inner(
                        country = '', 
                        start_year = 1.337, 
                        end_year = 1.337, 
                        start_factor = 1.337, 
                        end_factor = 1.337, 
                        change_pct = 1.337, 
                        projected = True, 
                        stats = currencycore.models.history_analysis_response_results_inner_stats.HistoryAnalysisResponse_results_inner_stats(
                            min = 1.337, 
                            max = 1.337, 
                            avg = 1.337, ), 
                        series = {
                            'key' : 1.337
                            }, 
                        note = '', )
                    ]
            )
        else:
            return PppAnalysisResponse(
                var_from = 1.337,
                to = 1.337,
                mode = 'compare',
                stats = True,
                results = [
                    currencycore.models.ppp_analysis_response_results_inner.PppAnalysisResponse_results_inner(
                        country = '', 
                        start_year = 1.337, 
                        end_year = 1.337, 
                        start_factor = 1.337, 
                        end_factor = 1.337, 
                        change_pct = 1.337, 
                        projected = True, 
                        stats = currencycore.models.history_analysis_response_results_inner_stats.HistoryAnalysisResponse_results_inner_stats(
                            min = 1.337, 
                            max = 1.337, 
                            avg = 1.337, ), 
                        series = {
                            'key' : 1.337
                            }, 
                        note = '', )
                    ],
        )
        """

    def testPppAnalysisResponse(self):
        """Test PppAnalysisResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
