# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.history_response import HistoryResponse

class TestHistoryResponse(unittest.TestCase):
    """HistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistoryResponse:
        """Test HistoryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistoryResponse`
        """
        model = HistoryResponse()
        if include_optional:
            return HistoryResponse(
                currency = '',
                base = '',
                interval = 'daily',
                var_from = '',
                to = '',
                rates = {
                    'key' : 1.337
                    }
            )
        else:
            return HistoryResponse(
                currency = '',
                base = '',
                interval = 'daily',
                var_from = '',
                to = '',
                rates = {
                    'key' : 1.337
                    },
        )
        """

    def testHistoryResponse(self):
        """Test HistoryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
