# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.api_error import ApiError

class TestApiError(unittest.TestCase):
    """ApiError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiError:
        """Test ApiError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiError`
        """
        model = ApiError()
        if include_optional:
            return ApiError(
                error = currencycore.models.api_error_error.ApiError_error(
                    code = '', 
                    message = '', 
                    details = null, )
            )
        else:
            return ApiError(
                error = currencycore.models.api_error_error.ApiError_error(
                    code = '', 
                    message = '', 
                    details = null, ),
        )
        """

    def testApiError(self):
        """Test ApiError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
