# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.convert_response import ConvertResponse

class TestConvertResponse(unittest.TestCase):
    """ConvertResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvertResponse:
        """Test ConvertResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvertResponse`
        """
        model = ConvertResponse()
        if include_optional:
            return ConvertResponse(
                var_from = '',
                from_country = '',
                amount = 1.337,
                var_date = '',
                requested_date = '',
                as_of = {
                    'key' : ''
                    },
                results = [
                    currencycore.models.convert_response_results_inner.ConvertResponse_results_inner(
                        to = '', 
                        to_country = '', 
                        result = 1.337, 
                        rate = 1.337, 
                        ppp = null, )
                    ],
                message = ''
            )
        else:
            return ConvertResponse(
                var_from = '',
                amount = 1.337,
                var_date = '',
                results = [
                    currencycore.models.convert_response_results_inner.ConvertResponse_results_inner(
                        to = '', 
                        to_country = '', 
                        result = 1.337, 
                        rate = 1.337, 
                        ppp = null, )
                    ],
        )
        """

    def testConvertResponse(self):
        """Test ConvertResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
