# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from currencycore.models.safe_haven_response import SafeHavenResponse

class TestSafeHavenResponse(unittest.TestCase):
    """SafeHavenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SafeHavenResponse:
        """Test SafeHavenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SafeHavenResponse`
        """
        model = SafeHavenResponse()
        if include_optional:
            return SafeHavenResponse(
                base = '',
                var_from = '',
                to = '',
                crisis = currencycore.models.safe_haven_response_crisis.SafeHavenResponse_crisis(
                    label = '', 
                    from = '', 
                    to = '', ),
                universe = 'liquid',
                results = [
                    currencycore.models.safe_haven_response_results_inner.SafeHavenResponse_results_inner(
                        currency = '', 
                        score = 1.337, 
                        volatility = 1.337, 
                        max_drawdown_pct = 1.337, 
                        crisis_return_pct = 1.337, 
                        note = '', )
                    ]
            )
        else:
            return SafeHavenResponse(
                base = '',
                var_from = '',
                to = '',
                crisis = currencycore.models.safe_haven_response_crisis.SafeHavenResponse_crisis(
                    label = '', 
                    from = '', 
                    to = '', ),
                results = [
                    currencycore.models.safe_haven_response_results_inner.SafeHavenResponse_results_inner(
                        currency = '', 
                        score = 1.337, 
                        volatility = 1.337, 
                        max_drawdown_pct = 1.337, 
                        crisis_return_pct = 1.337, 
                        note = '', )
                    ],
        )
        """

    def testSafeHavenResponse(self):
        """Test SafeHavenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
