# coding: utf-8

# flake8: noqa

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "CurrencyCoreApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AiResponse",
    "ApiError",
    "ApiErrorError",
    "ConvertResponse",
    "ConvertResponseResultsInner",
    "ConvertResponseResultsInnerPpp",
    "ConvertResponseResultsInnerPppAnyOf",
    "ConvertResponseResultsInnerPppAnyOf1",
    "CorrelationResponse",
    "CorrelationResponseResultsInner",
    "CountriesResponseInner",
    "CurrenciesResponseInner",
    "DrawdownResponse",
    "DrawdownResponseResultsInner",
    "HistoryAnalysisResponse",
    "HistoryAnalysisResponseResultsInner",
    "HistoryAnalysisResponseResultsInnerStats",
    "HistoryResponse",
    "MeanReversionResponse",
    "MeanReversionResponseResultsInner",
    "PppAnalysisResponse",
    "PppAnalysisResponseResultsInner",
    "RatesByBaseResponse",
    "RatesByBaseResponsePpp",
    "RatesResponse",
    "SafeHavenResponse",
    "SafeHavenResponseCrisis",
    "SafeHavenResponseResultsInner",
    "VolatilityResponse",
    "VolatilityResponseResultsInner",
]

# import apis into sdk package
from currencycore.api.currency_core_api import CurrencyCoreApi as CurrencyCoreApi

# import ApiClient
from currencycore.api_response import ApiResponse as ApiResponse
from currencycore.api_client import ApiClient as ApiClient
from currencycore.configuration import Configuration as Configuration
from currencycore.exceptions import OpenApiException as OpenApiException
from currencycore.exceptions import ApiTypeError as ApiTypeError
from currencycore.exceptions import ApiValueError as ApiValueError
from currencycore.exceptions import ApiKeyError as ApiKeyError
from currencycore.exceptions import ApiAttributeError as ApiAttributeError
from currencycore.exceptions import ApiException as ApiException

# import models into sdk package
from currencycore.models.ai_response import AiResponse as AiResponse
from currencycore.models.api_error import ApiError as ApiError
from currencycore.models.api_error_error import ApiErrorError as ApiErrorError
from currencycore.models.convert_response import ConvertResponse as ConvertResponse
from currencycore.models.convert_response_results_inner import ConvertResponseResultsInner as ConvertResponseResultsInner
from currencycore.models.convert_response_results_inner_ppp import ConvertResponseResultsInnerPpp as ConvertResponseResultsInnerPpp
from currencycore.models.convert_response_results_inner_ppp_any_of import ConvertResponseResultsInnerPppAnyOf as ConvertResponseResultsInnerPppAnyOf
from currencycore.models.convert_response_results_inner_ppp_any_of1 import ConvertResponseResultsInnerPppAnyOf1 as ConvertResponseResultsInnerPppAnyOf1
from currencycore.models.correlation_response import CorrelationResponse as CorrelationResponse
from currencycore.models.correlation_response_results_inner import CorrelationResponseResultsInner as CorrelationResponseResultsInner
from currencycore.models.countries_response_inner import CountriesResponseInner as CountriesResponseInner
from currencycore.models.currencies_response_inner import CurrenciesResponseInner as CurrenciesResponseInner
from currencycore.models.drawdown_response import DrawdownResponse as DrawdownResponse
from currencycore.models.drawdown_response_results_inner import DrawdownResponseResultsInner as DrawdownResponseResultsInner
from currencycore.models.history_analysis_response import HistoryAnalysisResponse as HistoryAnalysisResponse
from currencycore.models.history_analysis_response_results_inner import HistoryAnalysisResponseResultsInner as HistoryAnalysisResponseResultsInner
from currencycore.models.history_analysis_response_results_inner_stats import HistoryAnalysisResponseResultsInnerStats as HistoryAnalysisResponseResultsInnerStats
from currencycore.models.history_response import HistoryResponse as HistoryResponse
from currencycore.models.mean_reversion_response import MeanReversionResponse as MeanReversionResponse
from currencycore.models.mean_reversion_response_results_inner import MeanReversionResponseResultsInner as MeanReversionResponseResultsInner
from currencycore.models.ppp_analysis_response import PppAnalysisResponse as PppAnalysisResponse
from currencycore.models.ppp_analysis_response_results_inner import PppAnalysisResponseResultsInner as PppAnalysisResponseResultsInner
from currencycore.models.rates_by_base_response import RatesByBaseResponse as RatesByBaseResponse
from currencycore.models.rates_by_base_response_ppp import RatesByBaseResponsePpp as RatesByBaseResponsePpp
from currencycore.models.rates_response import RatesResponse as RatesResponse
from currencycore.models.safe_haven_response import SafeHavenResponse as SafeHavenResponse
from currencycore.models.safe_haven_response_crisis import SafeHavenResponseCrisis as SafeHavenResponseCrisis
from currencycore.models.safe_haven_response_results_inner import SafeHavenResponseResultsInner as SafeHavenResponseResultsInner
from currencycore.models.volatility_response import VolatilityResponse as VolatilityResponse
from currencycore.models.volatility_response_results_inner import VolatilityResponseResultsInner as VolatilityResponseResultsInner

