# coding: utf-8

# flake8: noqa
"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from currencycore.models.ai_response import AiResponse
from currencycore.models.api_error import ApiError
from currencycore.models.api_error_error import ApiErrorError
from currencycore.models.convert_response import ConvertResponse
from currencycore.models.convert_response_results_inner import ConvertResponseResultsInner
from currencycore.models.convert_response_results_inner_ppp import ConvertResponseResultsInnerPpp
from currencycore.models.convert_response_results_inner_ppp_any_of import ConvertResponseResultsInnerPppAnyOf
from currencycore.models.convert_response_results_inner_ppp_any_of1 import ConvertResponseResultsInnerPppAnyOf1
from currencycore.models.correlation_response import CorrelationResponse
from currencycore.models.correlation_response_results_inner import CorrelationResponseResultsInner
from currencycore.models.countries_response_inner import CountriesResponseInner
from currencycore.models.currencies_response_inner import CurrenciesResponseInner
from currencycore.models.drawdown_response import DrawdownResponse
from currencycore.models.drawdown_response_results_inner import DrawdownResponseResultsInner
from currencycore.models.history_analysis_response import HistoryAnalysisResponse
from currencycore.models.history_analysis_response_results_inner import HistoryAnalysisResponseResultsInner
from currencycore.models.history_analysis_response_results_inner_stats import HistoryAnalysisResponseResultsInnerStats
from currencycore.models.history_response import HistoryResponse
from currencycore.models.mean_reversion_response import MeanReversionResponse
from currencycore.models.mean_reversion_response_results_inner import MeanReversionResponseResultsInner
from currencycore.models.ppp_analysis_response import PppAnalysisResponse
from currencycore.models.ppp_analysis_response_results_inner import PppAnalysisResponseResultsInner
from currencycore.models.rates_by_base_response import RatesByBaseResponse
from currencycore.models.rates_by_base_response_ppp import RatesByBaseResponsePpp
from currencycore.models.rates_response import RatesResponse
from currencycore.models.safe_haven_response import SafeHavenResponse
from currencycore.models.safe_haven_response_crisis import SafeHavenResponseCrisis
from currencycore.models.safe_haven_response_results_inner import SafeHavenResponseResultsInner
from currencycore.models.volatility_response import VolatilityResponse
from currencycore.models.volatility_response_results_inner import VolatilityResponseResultsInner

