# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from currencycore.models.rates_by_base_response_ppp import RatesByBaseResponsePpp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RatesByBaseResponse(BaseModel):
    """
    RatesByBaseResponse
    """ # noqa: E501
    base: StrictStr
    var_date: StrictStr = Field(alias="date")
    requested_date: Optional[StrictStr] = Field(default=None, alias="requestedDate")
    as_of: Optional[Dict[str, StrictStr]] = Field(default=None, alias="asOf")
    rates: Dict[str, Union[StrictFloat, StrictInt]]
    ppp: Optional[RatesByBaseResponsePpp] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["base", "date", "requestedDate", "asOf", "rates", "ppp"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RatesByBaseResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ppp
        if self.ppp:
            _dict['ppp'] = self.ppp.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RatesByBaseResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "base": obj.get("base"),
            "date": obj.get("date"),
            "requestedDate": obj.get("requestedDate"),
            "asOf": obj.get("asOf"),
            "rates": obj.get("rates"),
            "ppp": RatesByBaseResponsePpp.from_dict(obj["ppp"]) if obj.get("ppp") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


