# coding: utf-8

"""
    CurrencyCore API

    Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from currencycore.models.volatility_response_results_inner import VolatilityResponseResultsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VolatilityResponse(BaseModel):
    """
    VolatilityResponse
    """ # noqa: E501
    base: StrictStr
    var_from: StrictStr = Field(alias="from")
    to: StrictStr
    mode: StrictStr
    sort: Optional[StrictStr] = None
    universe: Optional[StrictStr] = None
    basis: StrictStr
    results: List[VolatilityResponseResultsInner]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["base", "from", "to", "mode", "sort", "universe", "basis", "results"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['compare', 'ranking']):
            raise ValueError("must be one of enum values ('compare', 'ranking')")
        return value

    @field_validator('sort')
    def sort_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['stable', 'volatile']):
            raise ValueError("must be one of enum values ('stable', 'volatile')")
        return value

    @field_validator('universe')
    def universe_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['liquid', 'majors']):
            raise ValueError("must be one of enum values ('liquid', 'majors')")
        return value

    @field_validator('basis')
    def basis_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['annualized-daily']):
            raise ValueError("must be one of enum values ('annualized-daily')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VolatilityResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item_results in self.results:
                if _item_results:
                    _items.append(_item_results.to_dict())
            _dict['results'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VolatilityResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "base": obj.get("base"),
            "from": obj.get("from"),
            "to": obj.get("to"),
            "mode": obj.get("mode"),
            "sort": obj.get("sort"),
            "universe": obj.get("universe"),
            "basis": obj.get("basis"),
            "results": [VolatilityResponseResultsInner.from_dict(_item) for _item in obj["results"]] if obj.get("results") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


